[auth]
redirect_uri = "https://stocksense-ai-valndznxuspmwexhpqoo5i.streamlit.app/oauth2callback"
cookie_secret = "pP3kK7x9Qw2Zt8L1sR4vB6nY0cD5mH7fG9jK2pL4sT8wX1zR3"
client_id = "859390437000-33ijft9hv6mi7v65glbmejdl8e34eims.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
[alphavantage]
api_key = "JHNW62Y1MI9B6RCX"
