[auth]
redirect_uri = "https://stocksense-ai-valndznxuspmwexhpqoo5i.streamlit.app/oauth2callback"
cookie_secret = "pP3kK7x9Qw2Zt8L1sR4vB6nY0cD5mH7fG9jK2pL4sT8wX1zR3"
client_id = "TO_BE_FILLED_FROM_GOOGLE"
client_secret = "TO_BE_FILLED_FROM_GOOGLE"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
